import asyncio
import json
import os
import base64
import requests
from mcp.server.fastmcp import FastMCP
from search_xhs import search_and_extract_multiple

# 获取当前脚本绝对路径目录
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# 配置文件绝对路径
CONFIG_FILE = os.path.join(BASE_DIR, "config.json")
if os.path.exists(CONFIG_FILE):
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        config = json.load(f)
else:
    print(f"❌ 找不到配置文件 {CONFIG_FILE}！")
    exit(1)

VISION_TEXT_THRESHOLD = config.get("vision_text_threshold", 100)


def url_to_base64(image_url):
    try:
        response = requests.get(image_url, timeout=10)
        response.raise_for_status()
        return base64.b64encode(response.content).decode("utf-8")
    except Exception:
        return None


# 初始化 MCP Server
mcp = FastMCP("SweetPotatoLens")


@mcp.tool()
async def search_xiaohongshu(
    keywords: list[str], num_notes: int = 3, client_supports_vision: bool = False
) -> str:
    """
    Search Xiaohongshu (Little Red Book) with multiple keywords concurrently and extract note contents.

    CRITICAL INSTRUCTION FOR THE LLM CALLING THIS TOOL:
    1. When a user makes a request, DO NOT just pass their raw sentence as a single keyword. You MUST deeply understand their intent and generate an array of 2-3 highly optimized, specific, and distinct search keywords suitable for the Xiaohongshu platform. Pass these 2-3 keywords in the `keywords` array parameter.
    2. Assess your own capabilities: If YOU (the LLM) possess native Vision/Multimodal capabilities allowing you to read Base64 images from tool responses, set `client_supports_vision` to True. The tool will then intelligently download critical images and attach them as Base64 strings in the response for YOU to analyze. If you are a text-only model, set it to False to save bandwidth and use the text-only fast mode.

    Args:
        keywords: A list of 2-3 optimized search keywords generated by YOU (the LLM).
        num_notes: Number of top notes to fetch for each keyword. Defaults to 3.
        client_supports_vision: Set to True ONLY if you have multimodal capabilities to process Base64 images attached in the tool response.

    Returns:
        A JSON string containing the extracted notes (title, content, url, image_url, and conditionally base64_image).
    """
    # 检查状态文件是否存在
    STATE_FILE = os.path.join(BASE_DIR, "xhs_state.json")
    if not os.path.exists(STATE_FILE):
        return json.dumps(
            {
                "error": "Authentication state not found. The user needs to run login_xhs.py first to generate xhs_state.json."
            },
            ensure_ascii=False,
        )

    try:
        # 调用核心爬虫逻辑
        notes_data = await search_and_extract_multiple(keywords, num_notes=num_notes)

        if not notes_data:
            return json.dumps(
                {"message": "No notes found for the provided keywords."},
                ensure_ascii=False,
            )

        # 核心逻辑：如果大模型承认自己有视觉能力，我们把图片下载并转码塞给它
        if client_supports_vision:
            for note in notes_data:
                # 只有当笔记文字极少（干货藏在图里），并且确实抓到了图片链接时，才耗费带宽下载图
                if (
                    note.get("image_url")
                    and len(note.get("content", "")) < VISION_TEXT_THRESHOLD
                ):
                    base64_img = url_to_base64(note["image_url"])
                    if base64_img:
                        note["base64_image"] = f"data:image/jpeg;base64,{base64_img}"
                        note["content"] += (
                            "\n[ Note: The text is short. An image has been attached in the 'base64_image' field. Please analyze it. ]"
                        )

        # 返回 JSON 字符串给调用此 MCP 工具的大模型客户端
        return json.dumps(
            {"status": "success", "total_notes": len(notes_data), "data": notes_data},
            ensure_ascii=False,
            indent=2,
        )

    except Exception as e:
        return json.dumps(
            {"error": f"An error occurred during extraction: {str(e)}"},
            ensure_ascii=False,
        )


if __name__ == "__main__":
    # 启动 MCP Server (默认通过 stdio 与客户端通信)
    print("Starting SweetPotatoLens MCP Server...")
    mcp.run()
